server:
  port: 8088


spring:
  datasource:
    mysql:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://123.60.186.220:3306/zm_501_v2?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: health
      druid:
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
    clickhouse:
      driverClassName: com.clickhouse.jdbc.ClickHouseDriver
      enabled: true
      url: jdbc:clickhouse://116.63.207.41:9009/db_13?max_connections=10&compress=0
      username: default
      password: health
      druid:
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
  kafka:
    bootstrap-servers: 116.63.107.133:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      compress-type: gzip
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  config-location: classpath*:mapper/**/*.xml
